### ISSUE TITLE
Does not work with Vaadin 7.7.4

### ISSUE THREAD

**Issue by rbuchli** [caalador/TimeSelector#7]
Since my update to Vaadin 7.7.4 I get the following error running my application:

Caused by: java.lang.ClassCastException: org.percepta.mgrankvi.client.TimeSelectorState cannot be cast to com.vaadin.shared.ui.customfield.CustomFieldState
	at com.vaadin.ui.CustomField.getState(CustomField.java:162)
	at com.vaadin.ui.CustomField.getState(CustomField.java:47)
	at com.vaadin.server.AbstractClientConnector.getState(AbstractClientConnector.java:239)
	at com.vaadin.ui.AbstractComponent.getState(AbstractComponent.java:748)
	at com.vaadin.ui.AbstractField.getState(AbstractField.java:1732)
	at com.vaadin.ui.CustomField.getState(CustomField.java:157)
	at com.vaadin.ui.CustomField.getState(CustomField.java:47)
	at org.percepta.mgrankvi.TimeSelector.getState(TimeSelector.java:58)
	at org.percepta.mgrankvi.TimeSelector.getState(TimeSelector.java:19)
	at com.vaadin.ui.AbstractComponent.setImmediate(AbstractComponent.java:487)
	at com.vaadin.ui.AbstractComponent.readDesign(AbstractComponent.java:1016)
	at com.vaadin.ui.AbstractField.readDesign(AbstractField.java:1810)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:520)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:500)
	at com.vaadin.ui.AbstractOrderedLayout.readDesign(AbstractOrderedLayout.java:495)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:520)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:500)
	at com.vaadin.ui.AbstractOrderedLayout.readDesign(AbstractOrderedLayout.java:495)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:520)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:500)
	at com.vaadin.ui.CssLayout.readDesign(CssLayout.java:374)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:520)
	at com.vaadin.ui.declarative.Design.designToComponentTree(Design.java:483)
	at com.vaadin.ui.declarative.Design.read(Design.java:586)
	at ch.ludit.hangmuren.form.Tab14ZeitinfoDesign.<init>(Tab14ZeitinfoDesign.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.vaadin.ui.declarative.Design$DefaultComponentFactory.createComponent(Design.java:174)
	... 76 more

Seems not to be compatible anymore.
Would it be possible to make this plugin compatible to the newest Vaadin version?

Many Thanks
Reto

**Comment by caalador** [comment]
This is a "issue" in the framework as minor releases shouldn't bring these kind of changes.
This should be amended in 7.7.5 [#20468](https://dev.vaadin.com/ticket/20468)

In the mean time stick to 7.7.3 as I can't mark the component as functioning for minor versions.

**Comment by caalador** [comment]
Released 1.2.1 and tested with 7.7.5 with no problems.
